[package]
name = "listprocs"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5", features = ["wrap_help", "derive"] }
libc = "0.2"
regex = "1.10"
terminal_size = "0.3"